### ISSUE TITLE
Connection refused over ws

### ISSUE THREAD

**Issue by vinistoisr** [labbsr0x/traefik-letsencrypt-mqtt#2]
I used your example and am a bit stuck that I can't connect to the websockets

in the traefik logs everything is normal but then the verneMQ container refuses the connection:

time="2019-12-28T01:57:26Z" level=debug msg="'502 Bad Gateway' caused by: dial tcp 172.18.0.9:8080: connect: connection refused"

What URL and port are we supposed to connect to?

ws://vernemq.myhost.com:80/mqtt
wss://vernemq.myhost.com:443/mqtt

Testing using MQTT Explorer, when you choose websockets, you can't edit the url to wss://
Testing using the HiveHQ client, again there seems to be no way to enter the URL to make it work.
Testing in node-red when you use a wss url you need to provide the cert files

**Comment by tiagostutz** [comment]
Hi @VinistoisR
Just checked and there are some issues indeed, not related to the Bad Gateway you mentioned but with the Lets Encrypt hand shake:

```
traefik_1    | time="2019-12-28T21:14:08Z" level=error msg="Unable to obtain ACME certificate for domains \"verne.mqtt.testdomain.com\" detected thanks to rule \"Host:verne.mqtt.testdomain.com\" : cannot obtain certificates: acme: Error -> One or more domains had a problem:\n[] acme: Error 405 - urn:ietf:params:acme:error:malformed - Method not allowed\n"
```

I don't know yet what the problem is, but looks like something related to LE certbot version... we'll check it out. 

Meanwhile, I've fixed some a minor issues with VernMQ image which now enforces the users to accept license EULA by providing the environment var  `DOCKER_VERNEMQ_ACCEPT_EULA=yes` (check this for more information: https://vernemq.com/blog/2019/11/26/vernemq-end-user-license-agreement.html)

Just check the updated `docker-compose.yml`

I'll keep this issue opened until we have fixed the issue with

**Comment by tiagostutz** [comment]
Just checked here and definitely there are lots of changes in Traefik/Lets Encrypt that we must be updated to...

@ralphg6 how about putting this issue on the "OpenSource Rally"? In fact the job to be done is in https://github.com/tiagostutz/docker-traefik-letsencrypt/issues/2

**Comment by vinistoisr** [comment]
Yeah traefik 2 brings fixes for websockets, but it also requires re-writing of many other existing configurations, so I've been holding off on that.

**Comment by vinistoisr** [comment]
Can close this issue, it all works as-is with traefik 1.7.  I'm able to connect over secure ws with a valid cert.  You don't have to do anything with cert files in any of the apps, traefik handles it, and the auth, and all.

**Comment by qqtyin** [comment]
Hi, 

I have ran into the issue where traefik is unable to get certs with version 1.7, just like in the case of the OP. 

As I have read, acme v1 is being phased out. Traefik 1.7 does not support v2
https://letsencrypt.org/docs/client-options/

I think re-writing will be unavoidable at this stage for this solution to work.
